name: Node.js CI

on:
  pull_request:
    branches: [ "**" ] # Trigger on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x] # Use Node.js 22.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use 'ci' for cleaner installs based on package-lock.json

    - name: Run unit tests
      run: npm test

